name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint and check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm biome ci
      - run: pnpm typecheck

  test:
    name: Test and report coverage
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
      - uses: pnpm/action-setup@v4
      - uses: coverallsapp/github-action@v2
      - run: pnpm install
      - run: pnpm vitest --coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          comment-on: "pr"
