name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint and check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Prepare tools
        uses: pnpm/action-setup@v4
      - name: Run linting and type checking
        run: |
          pnpm install
          pnpm biome ci
          pnpm typecheck
          pnpm attw

  test:
    name: Test and report coverage
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Prepare tools
        uses: pnpm/action-setup@v4
      - name: Run tests
        run: |
          pnpm install
          pnpm install coveralls
          pnpm vitest --run --coverage
      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          comment-on: "pr"
      - name: Report coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ./coverage/lcov.info
